apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argocd
  labels:
    argocd-app: rke2-appset-projects-local
spec:
  description: Network projects
  sourceRepos:
  - https://github.com/kevinkychiu/kube-argocd.git
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
