apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-address-pool
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-895"
spec:
  project: network
  info:
    - name: Helm Chart URL
      value: https://github.com/kevinkychiu/kube-argocd/charts/metallb-address-pool
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
  source:
    path: charts/metallb-addresspool
    repoURL: https://github.com/kevinkychiu/kube-argocd.git
    targetRevision: HEAD
