apiVersion: batch/v1
kind: Job
metadata:
  name: read-vault-init-log-job
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      containers:
      - name: read-init-log-job
        # Use an image with kubectl pre-installed, e.g., bitnami/kubectl
        image: bitnami/kubectl:latest
        #volumeMounts:
        #- name: log-volume
        #  mountPath: /job/log
        command:
        - "/bin/bash"
        - "-c"
        # The actual kubectl command to run
        - |
          echo "read-init-log-job ..."
          NAMESPACE=vault
          LABEL=batch.kubernetes.io/job-name=vault-init
          POD_NAME=$(kubectl get pod -n $NAMESPACE -l $LABEL -o jsonpath="{.items[0].metadata.name}")
          echo POD_NAME: $POD_NAME
          ROOT_TOKEN=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Initial Root Token:" | awk -F": " '{print $2}')
          UNSEAL_KEY_1=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 1:" | awk -F": " '{print $2}')
          UNSEAL_KEY_2=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 2:" | awk -F": " '{print $2}')
          UNSEAL_KEY_3=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 3:" | awk -F": " '{print $2}')
          UNSEAL_KEY_4=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 4:" | awk -F": " '{print $2}')
          UNSEAL_KEY_5=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 5:" | awk -F": " '{print $2}')

          kubectl logs -n $NAMESPACE $POD_NAME \
            | jq -R -s '{log: .}' \
            | jq --arg val "$ROOT_TOKEN" '. + {root_token: $val}' \
            | jq --arg val "$UNSEAL_KEY_1" '. + {unseal_key_1: $val}' \
            | jq --arg val "$UNSEAL_KEY_2" '. + {unseal_key_2: $val}' \
            | jq --arg val "$UNSEAL_KEY_3" '. + {unseal_key_3: $val}' \
            | jq --arg val "$UNSEAL_KEY_4" '. + {unseal_key_4: $val}' \
            | jq --arg val "$UNSEAL_KEY_5" '. + {unseal_key_5: $val}' > /tmp/vault-init.log

          RETURN=$?
          echo RETURN: $RETURN

          echo "Create secret"
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: vault-init-log
            namespace: vault
            annotations:
              argocd.argoproj.io/tracking-id: vault:apps/Secret:argocd/read-vault-init-log-job
            labels:
              argocd-app: vault
          type: Opaque
          data:
            LOG: |
              $(cat /tmp/vault-init.log | base64 -w 0)
            VAULT_TOKEN: $(echo $ROOT_TOKEN | base64 -w 0)
            UNSEAL_KEY_1: $(echo $UNSEAL_KEY_1 | base64 -w 0)
            UNSEAL_KEY_2: $(echo $UNSEAL_KEY_2 | base64 -w 0)
            UNSEAL_KEY_3: $(echo $UNSEAL_KEY_3 | base64 -w 0)
            UNSEAL_KEY_4: $(echo $UNSEAL_KEY_4 | base64 -w 0)
            UNSEAL_KEY_5: $(echo $UNSEAL_KEY_5 | base64 -w 0)
          EOF

          exit $RETURN
      #volumes:
      #- name: log-volume
      #  emptyDir: {}
      #   secret:
      #     secretName: metallb-system
      restartPolicy: Never # Job should terminate after completion
  backoffLimit: 3 # Optional: specify retry limits
