apiVersion: batch/v1
kind: Job
metadata:
  name: read-init-log-job
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  template:
    spec:
      serviceAccountName: vault
      containers:
      - name: read-init-log-job
        # Use an image with kubectl pre-installed, e.g., bitnami/kubectl
        image: bitnami/kubectl:latest
        command:
        - "/bin/bash"
        - "-c"
        # The actual kubectl command to run
        - |
          NAMESPACE=vault
          LABEL=batch.kubernetes.io/job-name=vault-init
          POD_NAME=$(kubectl get pod -n $NAMESPACE -l $LABEL -o jsonpath="{.items[0].metadata.name}")
          echo POD_NAME: $POD_NAME
          ROOT_TOKEN=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Initial Root Token:" | awk -F": " '{print $2}')
          echo "Done."
      # volumes:
      # - name: metallb-system
      #   secret:
      #     secretName: metallb-system
      restartPolicy: Never # Job should terminate after completion
  backoffLimit: 4 # Optional: specify retry limits
