apiVersion: batch/v1
kind: Job
metadata:
  name: read-vault-init-log-job
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      containers:
      - name: read-init-log-job
        # Use an image with kubectl pre-installed, e.g., bitnami/kubectl
        image: bitnami/kubectl:latest
        volumeMounts:
        - name: log-volume
          mountPath: /job/log
        command:
        - "/bin/bash"
        - "-c"
        # The actual kubectl command to run
        - |
          NAMESPACE=vault
          LABEL=batch.kubernetes.io/job-name=vault-init
          POD_NAME=$(kubectl get pod -n $NAMESPACE -l $LABEL -o jsonpath="{.items[0].metadata.name}")
          echo POD_NAME: $POD_NAME
          ROOT_TOKEN=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Initial Root Token:" | awk -F": " '{print $2}')
          UNSEAL_KEY_1=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 1:" | awk -F": " '{print $2}')
          UNSEAL_KEY_2=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 2:" | awk -F": " '{print $2}')
          UNSEAL_KEY_3=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 3:" | awk -F": " '{print $2}')
          UNSEAL_KEY_4=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 4:" | awk -F": " '{print $2}')
          UNSEAL_KEY_5=$(kubectl logs -n $NAMESPACE $POD_NAME | grep "Unseal Key 5:" | awk -F": " '{print $2}')

          ls -l /job/log
          echo "test" > /job/log/test.log
          ls -l /job/log

          kubectl logs -n $NAMESPACE $POD_NAME \
            | jq -R -s '{log: .}' \
            | jq --arg val "$ROOT_TOKEN" '. + {root_token: $val}' \
            | jq --arg val "$UNSEAL_KEY_1" '. + {unseal_key_1: $val}' \
            | jq --arg val "$UNSEAL_KEY_2" '. + {unseal_key_2: $val}' \
            | jq --arg val "$UNSEAL_KEY_3" '. + {unseal_key_3: $val}' \
            | jq --arg val "$UNSEAL_KEY_4" '. + {unseal_key_4: $val}' \
            | jq --arg val "$UNSEAL_KEY_5" '. + {unseal_key_5: $val}' > /job/log/vault-init.log

          RETURN=$?
          echo RETURN: $RETURN
          exit $RETURN
      - name: process-init-log
        # Use an image with kubectl pre-installed, e.g., bitnami/kubectl
        image: bitnami/kubectl:latest
        volumeMounts:
        - name: log-volume
          mountPath: /job/log
        command:
        - "/bin/bash"
        - "-c"
        - |
          ls -l /job/log
          exit 0
      volumes:
      - name: log-volume
        emptyDir: {}
      #   secret:
      #     secretName: metallb-system
      restartPolicy: Never # Job should terminate after completion
  backoffLimit: 3 # Optional: specify retry limits
