apiVersion: batch/v1
kind: CronJob
metadata:
  name: unseal-vault-job
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 10
      template:
        spec:
          container:
            name: "vault-monitor"
            image: hashicorp/vault:1.18.1
            envFrom:
            - configMapRef:
                name: vault-config-map
            - secretRef:
                name: vault-init-log
          command:
          - "/bin/sh"
          - "-c"
          # The actual kubectl command to run
          - |
            echo "vault-monitor ..."
            KEYS="$UNSEAL_KEY_1 $UNSEAL_KEY_2 $UNSEAL_KEY_3 $UNSEAL_KEY_4 $UNSEAL_KEY_5"
            echo $KEYS

          restartPolicy: Never