

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool-argocd
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave=-899
spec:
  addresses:
    - 101.10.170.103/32

