apiVersion: batch/v1
kind: Job
metadata:
  name: address-pool-job
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      containers:
      - name: tester
        # Use an image with kubectl pre-installed, e.g., bitnami/kubectl
        image: bitnami/kubectl:latest
        envFrom:
        - secretRef:
            name: metallb-system
        env:
        - name: PRIMARY_ADDRESS_POOL
          valueFrom:
            secretKeyRef:
              name: metallb-system
              key: primary-address-pool
        - name: SECONDARY_ADDRESS_POOL
          valueFrom:
            secretKeyRef:
              name: metallb-system
              key: secondary-address-pool
        # volumeMounts:
        # - name: metallb-system
        #   mountPath: /etc/config
        #   readOnly: true
        command:
        - "/bin/bash"
        - "-c"
        # The actual kubectl command to run
        - |
          cat <<EOF > /tmp/test.yaml
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: primary-pool
            namespace: metallb-system
            annotations:
              argocd.argoproj.io/tracking-id: metallb-address-pool-job:apps/IPAddressPool:argocd/address-pool-job
            labels:
              argocd-app: address-pool-job
          spec:
            addresses:
              - "${PRIMARY_ADDRESS_POOL}"
          ---
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: secondary-pool
            namespace: metallb-system
            annotations:
              argocd.argoproj.io/tracking-id: metallb-address-pool-job:apps/IPAddressPool:argocd/address-pool-job
            labels:
              argocd-app: address-pool-job
          spec:
            addresses:
              - "${SECONDARY_ADDRESS_POOL}"
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-advert
            namespace: metallb-system
            annotations:
              argocd.argoproj.io/tracking-id: metallb-address-pool-job:apps/IPAddressPool:argocd/address-pool-job
            labels:
              argocd-app: address-pool-job
          spec:
            ipAddressPools:
              - primary-pool
              - secondary-pool
          EOF
          echo "YAML file created."
          kubectl apply -f /tmp/test.yaml
          kubectl get IPAddressPool -A
          kubectl get L2Advertisement -A
          echo "Done."
      # volumes:
      # - name: metallb-system
      #   secret:
      #     secretName: metallb-system
      restartPolicy: Never # Job should terminate after completion
  backoffLimit: 4 # Optional: specify retry limits
