apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-address-pool-job
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      restartPolicy: Never
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - echo "Cleaning up resources..."