apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-address-pool-job
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      restartPolicy: Never
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command:
            - "/bin/bash"
            - "-c"
            - |
              echo "Application deleted, running cleanup..."
              kubectl delete L2Advertisement -n metallb-system -l argocd-app=metallb-address-pool-job
              kubectl delete IPAddressPool -n metallb-system -l argocd-app=metallb-address-pool-job
              echo "Cleaning up resources..."
              sleep 60