apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Network projects
  sourceRepos:
  - https://github.com/kevinkychiu/kube-argocd.git
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
